site_name: Sundestova
site_url: https://sundestova.lund.store/
hide:
  - navigation
  - toc
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
  language: en
  palette:
   - scheme: default
     toggle:
       icon: material/toggle-switch-off-outline
       name: Switch to dark mode
     primary: teal
     accent: purple
   - scheme: slate
     toggle:
       icon: material/toggle-switch
       name: Switch to light mode
     primary: teal
     accent: lime

## MD_Extensions

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  generator: false
  homepage: https://airbnb.com/h/sundestova

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/milarn/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Milarngg
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/martin-k-l-4a3921130/

copyright: |
 &copy; 2023 <a href="https://github.com/milarn/" target="_blank" rel="noopener">Martin K. Lund</a>